### ISSUE TITLE
Checking stats when enemy(AI) is moving is throwing an exception

### ISSUE THREAD

**Issue by Mixss** [esoviscode/discord-dnd-bot#140]
![image](https://user-images.githubusercontent.com/19227717/224819582-647d8836-4761-4ede-8f49-a0403648c812.png)
![image](https://user-images.githubusercontent.com/19227717/224819619-f96b02d5-62bc-4d42-b971-42d4476d8806.png)

**Comment by Silentsky0** [comment]
fixed in #141
